### ISSUE TITLE
Max entries

### ISSUE THREAD

**Issue by MrCupola** [dr4ke616/MMM-Dublin-Bus#2]
Is there a way to set a maximum number of entries? I tried to add: maximumEntries: 3, but doesn't work :D 
I would like to have just 3/4 lines taken from the module 'cause I don't have so much space left in the mirror...
Thanks in advance for your time

**Comment by dr4ke616** [comment]
Nope, right now the plugin will just return all available rows. There is no logic to limit the result set.

**Comment by dr4ke616** [comment]
Reported in #5 Closing for now
